# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modelInputs.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11modelInputs.proto\x12\x0bmodelInputs\"\x95\x01\n\x06Member\x12\x15\n\rmember_offset\x18\x01 \x01(\r\x12#\n\x04type\x18\x02 \x01(\x0e\x32\x15.modelInputs.TypeSpec\x12\x0c\n\x04size\x18\x03 \x01(\r\x12\x13\n\ti64_value\x18\x04 \x01(\x12H\x00\x12\x11\n\x07\x66_value\x18\x05 \x01(\x02H\x00\x12\x11\n\x07\x64_value\x18\x06 \x01(\x01H\x00\x42\x06\n\x04\x64\x61ta\"2\n\nMemberList\x12$\n\x07members\x18\x01 \x03(\x0b\x32\x13.modelInputs.Member\"\xd9\x01\n\tGlobalVar\x12\x0e\n\x06offset\x18\x01 \x01(\r\x12\x0c\n\x04name\x18\x02 \x01(\t\x12#\n\x04type\x18\x03 \x01(\x0e\x32\x15.modelInputs.TypeSpec\x12\x0c\n\x04size\x18\x04 \x01(\r\x12\x0c\n\x04\x61\x64\x64r\x18\x05 \x01(\x04\x12\x13\n\ti64_value\x18\x06 \x01(\x12H\x00\x12\x11\n\x07\x66_value\x18\x07 \x01(\x02H\x00\x12\x11\n\x07\x64_value\x18\x08 \x01(\x01H\x00\x12*\n\x07members\x18\t \x01(\x0b\x32\x17.modelInputs.MemberListH\x00\x42\x06\n\x04\x64\x61ta\"\xd7\x01\n\x07HeapVar\x12\x0c\n\x04hash\x18\x01 \x01(\x04\x12\x0e\n\x06offset\x18\x02 \x01(\r\x12#\n\x04type\x18\x03 \x01(\x0e\x32\x15.modelInputs.TypeSpec\x12\x0c\n\x04size\x18\x04 \x01(\r\x12\x0c\n\x04\x61\x64\x64r\x18\x05 \x01(\x04\x12\x13\n\ti64_value\x18\x06 \x01(\x12H\x00\x12\x11\n\x07\x66_value\x18\x07 \x01(\x02H\x00\x12\x11\n\x07\x64_value\x18\x08 \x01(\x01H\x00\x12*\n\x07members\x18\t \x01(\x0b\x32\x17.modelInputs.MemberListH\x00\x42\x06\n\x04\x64\x61ta\"a\n\x0bModelInputs\x12*\n\nglobalVars\x18\x01 \x03(\x0b\x32\x16.modelInputs.GlobalVar\x12&\n\x08heapVars\x18\x02 \x03(\x0b\x32\x14.modelInputs.HeapVar*J\n\x08TypeSpec\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x07\n\x03INT\x10\x01\x12\t\n\x05\x46LOAT\x10\x02\x12\n\n\x06\x44OUBLE\x10\x03\x12\x07\n\x03PTR\x10\x04\x12\x08\n\x04\x41GGR\x10\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'modelInputs_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TYPESPEC._serialized_start=775
  _TYPESPEC._serialized_end=849
  _MEMBER._serialized_start=35
  _MEMBER._serialized_end=184
  _MEMBERLIST._serialized_start=186
  _MEMBERLIST._serialized_end=236
  _GLOBALVAR._serialized_start=239
  _GLOBALVAR._serialized_end=456
  _HEAPVAR._serialized_start=459
  _HEAPVAR._serialized_end=674
  _MODELINPUTS._serialized_start=676
  _MODELINPUTS._serialized_end=773
# @@protoc_insertion_point(module_scope)
